name: Deploy Documentation

on:
  push:
    branches:
      - latest
  workflow_dispatch:

concurrency:
  group: docs
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pages: write
    defaults:
      run:
        shell: bash
    env:
      NODE_VERSION: 22
      DOCS_DIR: ./Docs
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ${{ env.DOCS_DIR }}/package-lock.json
      - name: Install dependencies
        working-directory: ${{ env.DOCS_DIR }}
        run: npm clean-install
      - name: Build VuePress site
        working-directory: ${{ env.DOCS_DIR }}
        run: npm run build
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5  
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DOCS_DIR }}/.vuepress/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
