name: Deploy Documentation

on:
  push:
    branches:
      - latest
  workflow_dispatch:

concurrency:
  group: vuepress
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write
  pages: write

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      NODE_VERSION: 22
      DOCS_DIR: ./Docs
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ${{ env.DOCS_DIR }}/package-lock.json
      - name: Install npm dependencies
        working-directory: ${{ env.DOCS_DIR }}
        run: npm clean-install
      - name: Build VuePress static site
        working-directory: ${{ env.DOCS_DIR }}
        run: npm run build
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5  
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DOCS_DIR }}/.vuepress/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - name: Deploy artifact to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4
